### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by Cloud9G** [CADOJRP/FiveM-AdministrationPanel#13]
Upon installing it fresh editing the config to be correct, Added domain name. When loading the site i get this. PHP Notice:  Undefined index: createRoute in C:\inetpub\wwwroot\*REDACTED*\app\main\plugins.class.php on line 86
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in C:\inetpub\wwwroot\*REDACTED*\app\main\plugins.class.php on line 86

**Comment by avery1227** [comment]
Sorry for the late response. These are harmless errors and shouldn't change how it works.
