### ISSUE TITLE
Dashboard is broken

### ISSUE THREAD

**Issue by kloentje2** [CADOJRP/FiveM-AdministrationPanel#14]
This maybe seems like a strange issue, but I have tried a lot to solve this problem. 

The problem: An idiot (old staff member) had the guts to enter the server and do very bad stuff, so we got locked out from it. After that, I've managed to restore the access. 

But unfortunately, when I start the webserver and open the admin panel, I cannot open any tabs on an user page. It simply is ignoring my action. 

I tried to look for some errors in my console, but there aint no errors. 
Does anybody know how to solve this? We meet all of the server requirements.

Windows Server 2012 
Apache/MySQL via XAMPP 
FiveM server running on 30120 

Also when I access the cron page, I see 
> SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data

**Comment by avery1227** [comment]
I believe something is wrong with your database, I would re-upload the database (but no empty it so you still have your old data)

**Comment by kloentje2** [comment]
Hi Avery1227, I'm sorry that i've bothered you guys. The problem was solved by changing a SQL password
