### ISSUE TITLE
How to setup CRON job?

### ISSUE THREAD

**Issue by bartoszewski2** [CADOJRP/FiveM-AdministrationPanel#17]
Hello, im new in this, how to setup a cron job, as it is said in the third point "Setup a Cron job to run http://yoururl.com/api/cron every minute. (This adds 1 minute to the playing time if they're online)"

**Comment by ltmote** [comment]
You'd setup a cron through your shell window, or through cPanel if you have it... However there is no /cron/ folder or cron files in the upload, so I can't make the cron job either... no where to point it to.

**Comment by avery1227** [comment]
Hello, currently the best way to contact our support would be via our Discord server here: https://discord.gg/q8MSQwt
