### ISSUE TITLE
Index downlaods

### ISSUE THREAD

**Issue by Wolf1911** [CADOJRP/FiveM-AdministrationPanel#19]
Instead of opening up the page, it downloads a file.

[Here's the site.](http://mountaincommunityrp.com/fivemmanager/)

I believe I set up the config correctly.

**Comment by avery1227** [comment]
Try this .htaccess:

```
Options -MultiViews

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
AddType application/x-httpd-ea-php70 .php .php7 .phtml
```

**Comment by Wolf1911** [comment]
I cannot see the file to edit it, sadly.

**Comment by avery1227** [comment]
Alrighty, below is a zip file which inside will have the .htaccess file, you should be able to view it in the zip, if you upload the .htaccess from there or upload the zip through the cPanel file manager and unzip it, this might resolve the issue.

[file inside here.zip](https://github.com/CADOJRP/FiveM-AdministrationPanel/files/2825327/file.inside.here.zip)

**Comment by Wolf1911** [comment]
Alright, thanks a bunch. I'll try it now.

**Comment by Wolf1911** [comment]
Still seems to do it.

**Comment by Wolf1911** [comment]
I got it to work, the php was a couple versions behind on my end. Completely my idiocy! Thanks a whole lot for the help, even if it was a slight waste of time!

**Comment by Huntsleyjr** [comment]
Hello,
I appear to be having the same issue, i have fresh installs of MySQL, php 7.4, and Apache24.
I have tried to edit the  .htaccess but it still downloads a file

**Comment by Huntsleyjr** [comment]
I tried to upload the panel.sql again and recive this error 
Restoring C:\Users\###\Downloads\FiveM-AdministrationPanel-master\FiveM-AdministrationPanel-master\web\fivemad1_panel.sql
Running: mysql.exe --defaults-file="c:\users\###\appdata\local\temp\tmpr1xsth.cnf"  --protocol=tcp --host=localhost --user=root --port=3306 --default-character-set=utf8 --comments --database=fivem  < "C:\\Users\\###\\Downloads\\FiveM-AdministrationPanel-master\\FiveM-AdministrationPanel-master\\web\\fivemad1_panel.sql"
ERROR 1060 (42S21) at line 291: Duplicate column name 'active'

Operation failed with exitcode 1
11:37:26 Import of C:\Users\###\Downloads\FiveM-AdministrationPanel-master\FiveM-AdministrationPanel-master\web\fivemad1_panel.sql has finished with 1 errors
