### ISSUE TITLE
Cron Job

### ISSUE THREAD

**Issue by YesImsevy** [CADOJRP/FiveM-AdministrationPanel#20]
Need help setting up how to setup the cron job on cpanel it wont run since its not a real .php file

**Comment by Cloud9G** [comment]
You can try using your ip in the staff resource https://IPHERE
In the config https://"IPHERE"/
May or may not work.

**Comment by avery1227** [comment]
Hello, currently the best way to contact our support would be via our Discord server here: https://discord.gg/q8MSQwt
