### ISSUE TITLE
PHP ERROR ON DASHBOARD

### ISSUE THREAD

**Issue by s0me114** [CADOJRP/FiveM-AdministrationPanel#21]
When i open the dashboard i get this : Notice: Undefined index: createRoute in C:\wamp64\www\staff\app\main\plugins.class.php on line 86

Warning: count(): Parameter must be an array or an object that implements Countable in C:\wamp64\www\staff\app\main\plugins.class.php on line 86

Notice: Undefined index: header in C:\wamp64\www\staff\app\main\plugins.class.php on line 86

Warning: count(): Parameter must be an array or an object that implements Countable in C:\wamp64\www\staff\app\main\plugins.class.php on line 86

error on top and on left bar where all the categories are.

**EDIT:** 
![error](https://user-images.githubusercontent.com/26486073/52729484-919dbd80-2fb9-11e9-80f2-1bdbaffd1567.JPG)

**Comment by Cloud9G** [comment]
go to the C:\wamp64\www\staff\app\main\plugins.class.php an on line 86 put a @ infront of (count so it looks like  if (@count(self::$plugins[$hook]) != 0) {

**Comment by Harrychandler71** [comment]
Hi, can someone please contact me on Discord and help me do this. I would greatly appreciate it. My discord is H. Chandler#7023

**Comment by avery1227** [comment]
Hello, currently the best way to contact our support would be via our Discord server here: https://discord.gg/q8MSQwt
