### ISSUE TITLE
Server shows as offline?

### ISSUE THREAD

**Issue by KingpinNetwork** [CADOJRP/FiveM-AdministrationPanel#29]
Hi, I have everything setup and all, but when I go to the servers list and click the server I want to view, it says the server is offline. Not sure what to do about it, no bans/kicks/warns etc work on players in-game. I have sent heartbeats as well so the server is definitely online.

**Comment by avery1227** [comment]
Sounds like port 30120 (or whatever your FiveM server port is ) is blocked on the web server. It could also not have CURL, Fsocket, or file_get_contents
