### ISSUE TITLE
Steam will Not connect with fivem server side resource & webpage will continuously redirect too steam auth

### ISSUE THREAD

**Issue by Breakdonw** [CADOJRP/FiveM-AdministrationPanel#3]
Steam will Not connect with fivem server side resource & webpage will continuously redirect too steam auth
Server is just running plain Dunko's Vrp nothing else.

**Comment by avery1227** [comment]
Steam is currently having issues. Please let me know if the issue persists after Steam API comes back online.

**Comment by Breakdonw** [comment]
Is there a way to check its status?

**Comment by Breakdonw** [comment]
Steam api never went down, and the issue still persist, we even switched the steamapi key

**Comment by Breakdonw** [comment]
I resolved this issue but ran into another
![image](https://user-images.githubusercontent.com/34593308/38711453-c3aa788a-3e93-11e8-88a2-9d739c1bf091.png)
I have a feeling this has something to do with css?

**Comment by avery1227** [comment]
Add a `/` at the end of domain name

**Comment by Breakdonw** [comment]
Thank you sorry for the bother!

**Comment by schwim0341** [comment]
Can you tell me how you resolved your Steam login loop?  I'm suffering the same issue.

![image](https://user-images.githubusercontent.com/15654144/41186608-67fabd50-6b67-11e8-9fca-541c0dfe240a.png)

**Comment by avery1227** [comment]
@schwim0341 From the image alone I see that Steam isn't getting the URL of the panel. In most cases, this is caused by something in the config is wrong.
