### ISSUE TITLE
Playtime function don't work

### ISSUE THREAD

**Issue by Erkom** [CADOJRP/FiveM-AdministrationPanel#30]
The function playtime don't work
![ScreenShot_20190420165613](https://user-images.githubusercontent.com/20351617/56461675-48893180-638d-11e9-9bbd-010b42562775.png) just stay in 1 minute for ever.

**Comment by DXNCXX** [comment]
Make sure Cron job is running

**Comment by rhys19** [comment]
Can confirm that i am receiving this issue aswell and cron is setup (cron job site & a ubuntu vps)
not sure if this is a common issue or not.

**Comment by rhys19** [comment]
don't download the master (Broken playtime hours) download the [release](https://github.com/CADOJRP/FiveM-AdministrationPanel/releases/tag/v0.4.1-hotfix) version that worked for me.

**Comment by Erkom** [comment]
the response for cron **{"status":"200","message":"Successful","loadtime":0.015176057815551758,"servers":0,"phpbin":"C:\nmpp\\php"}.**

But in my /api/userdata the response:
**{"error":"Missing Parameter","details":"Community ID Missing"}**

I use Windows Server 2016 and xampp

**Comment by CruelAlpha** [comment]
How was this solved?
