### ISSUE TITLE
Undefined offset: 0 || Cannot create community

### ISSUE THREAD

**Issue by tholeb** [CADOJRP/FiveM-AdministrationPanel#37]
Hi there, i installed the the panel on my webserver (Linux Debian 9) and i found those errors:
-  Undefined offset: 0 - http://prntscr.com/o89vtm
- "Create community" button does not work.

I didn't setup the cron job, but on my windows local server, i didn't had those errors (without cron job).

Thanks.

**Comment by BioSpinGaming** [comment]
Are you using nginx or apache?

**Comment by tholeb** [comment]
> Are you using nginx or apache?

I'm using apache2 and php 7.0.3 and for my localhost php 7.3.3. Arthur suggested that it was the .htaccess but i didn't touch anything :/ .

**Comment by Wortex** [comment]
Htaccess has a variable for php bin, make sure the path in htaccess is correct

**Comment by tholeb** [comment]
Ok, thanks i will check for that, but do you know how I can find the path (Windows and Linux)?

**Comment by HALALsnackbar** [comment]
We are also receiving this same issue on Linux UBUNTU 17. Offset 0 and the Create Community button does not work but it creates users in the database so I know the DB connection is fine.
