### ISSUE TITLE
Ranks not properly displayed on Add Staff

### ISSUE THREAD

**Issue by alphadeni** [CADOJRP/FiveM-AdministrationPanel#40]
Hey,
I'm using Hotfix 0.4.1. and when I go to /admin/staff the ranks aren't showing.

With my PHP knowledge I'm guessing that the json_decode() function is returning zero?
Keep in mind that I have _**not**_ changed the permissions field in the config table so I am pretty confused.

I did try running it through json_decode() externally and it hasn't been successful.

Anyone have a fix?

**Comment by avery1227** [comment]
I forget how I fixed it however I believe one of the variables was wrong.

**Comment by alphadeni** [comment]
Alright, will check it out and see what I can do, thanks.

**Comment by tholeb** [comment]
You do not see the ranks is that it ?

**Comment by alphadeni** [comment]
> You do not see the ranks is that it ?
> You can look at this file: https://github.com/CADOJRP/FiveM-AdministrationPanel/blob/master/web/app/pages/admin/staff.php
> 
> ```
> <select class="form-control" id="selectrank" name="rank">
>   <?php
>      foreach ($GLOBALS['permissions'] as $role=>$rank) {
>           echo '<option value="'.$role.'">'.$role.'</option>';
>      }
>    ?>
> </select>
> ```

Thank you very much, the problem was fixed by replacing the code.
