### ISSUE TITLE
Players dont get added to the player table when they connect

### ISSUE THREAD

**Issue by Lxk3y** [CADOJRP/FiveM-AdministrationPanel#49]
As the title says, for some reason no matter what i do (i follow all instructions and tried 2 different hosts including the recommended one, when a player joins the server they do NOT get added to the players table. I even tried running the http request for adding a user manually in the browser and it said 200 successfully added player to database but nothing... Online players show up on the panel, but no recent players are stored, and this means i cannot warn, kick or ban a player because none of there details are in the database

**Comment by Blizzard098** [comment]
Having the same exact issue.

**Comment by KacpereQ02** [comment]
Same here, fixed?
