### ISSUE TITLE
some pages blank

### ISSUE THREAD

**Issue by ResqDiver1317** [CADOJRP/FiveM-AdministrationPanel#56]
Our panel was working fine hosted at Vortex (elhs) but I decided to move it to the same server as our FiveM server is on (dedicated linux game server running ubuntu 18.04) to save the extra few $s a month we are paying to Vortex plus it just makes sense to me since we have the server ability, why not consolidate. Some things seem to work fine, but others do not. I can click on our server in the panel and see the current players, but when I click on the player to pull up their profile in the panel, I just get a blank page. Also, I can see the page to edit servers and edit the panel settings, but when I click to edit the staff, again I just get a blank page.
I know the self hosted version is not really supported anymore but I'm hoping someone can give me some advice on what would be causing this to happen like this.

**Comment by avery1227** [comment]
It sounds like some dependencies are missing. Have you verified everything is installed. Also double check that the .htaccess is correct

**Comment by avery1227** [comment]
### Requirements:
MySQL Server
PHP 7 or Newer
BCMath Ext
CURL Ext
FOPEN URL Enabled
Steam API Key
Ability to run Cron Jobs
Outgoing Ports (30120 / Server Port)

**Comment by ResqDiver1317** [comment]
I used phpinfo to check and I believe all the dependencies are in place but I’ll double check again when I get home. As far as .htaccess, that was an issue from the start I had to fight and I’ll have to double check that as well. Apache2 doesn’t seem to recognize .htaccess properly so I had to enable the rewrite rules in the sites .conf file

**Comment by ResqDiver1317** [comment]
After messing with it some more, I've found that anyone that it shows only 1 minute of playtime, it will load their panel profile fine. Anyone with 2 minutes or higher, I get the blank page.

**Comment by ResqDiver1317** [comment]
Got it. It was my fopen settings in my php.ini. Only 1 part of it was set to On. I set allow fopen url to On as well and it is working now :)
