### ISSUE TITLE
Steamp sign-in loop

### ISSUE THREAD

**Issue by schwim0341** [CADOJRP/FiveM-AdministrationPanel#7]
Hi there, 

I posted in someone else's issue before realizing it had been closed so I thought I should open a new one.

After installing the web script, Upon first visiting my page, I'm directed to the Steam login.  The issue is that the login loops with a totally unhelpful error message of "Error"

![image](https://user-images.githubusercontent.com/15654144/41186645-0c1db144-6b68-11e8-8193-67d37da0fba7.png)

Any idea of what's going on?  I did fill in my API key as well as all the other info in config.php

Thanks for your time!

**Comment by avery1227** [comment]
It would seem something in the config.php file is wrong. Most likely something to do with the URL, subdomain, and or subfolder.

**Comment by schwim0341** [comment]
It was indeed an error on my part. Thank you so much for taking the time to help me out!
